version: "3.2"
services:
    reverseproxy:
        container_name: reverseproxy
        build: .
        ports:
            - 8081:8081
            - 8082:8082
        restart: always
        
    nginx:
        container_name: nginxweb
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    apache:
        container_name: apache
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always

